# version: 0.2

# phases:
#   install:
#     commands:
#       - npm install
#   build:
#     commands:
#       - echo "Build started on `date`"
#       - node index.js &
#   post_build:
#     commands:
#       - echo "Build completed on `date`"

# artifacts:
#   files:
#     - "**/*"
